apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-policy
spec:
  type: policyproject
  contents: UEsDBAoAAAAAADRsVFUAAAAAAAAAAAAAAAAXABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAkAAzROUWNtTlFjdXgLAAEE/v8AAAT+/wAAUEsDBBQACAAIADRsVFUAAAAAAAAAAPIAAAArABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUCQADNE5RYzROUWN1eAsAAQT+/wAABP7/AABdjjsOwjAMhndOEWVvU7aq6mMBRqZygJAYiEidKE4LvT2pCkIwWfb/8Fd3z8GyCQIZhw3f5gVngMppg9eGn/pDVvKu3dTeWaMMULthbF1mto5+9pCcBGEHF4Og+Vs4yiEJZ6nugHoM9nPvYfBWxr/QUpyqyUm/R+2dwdjeYvSVEMstORNkhg4J1Bggj85ZymlSVVmUhXhQLX6yC6dYHyZ88eV/AVBLBwgyw5h4pAAAAPIAAABQSwECHgMKAAAAAAA0bFRVAAAAAAAAAAAAAAAAFwAYAAAAAAAAABAA7UEAAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAUAAzROUWN1eAsAAQT+/wAABP7/AABQSwECHgMUAAgACAA0bFRVMsOYeKQAAADyAAAAKwAYAAAAAAABAAAApIFRAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUBQADNE5RY3V4CwABBP7/AAAE/v8AAFBLBQYAAAAAAgACAM4AAABqAQAAAAA=
